! ============================================
! mac-speaker FRR BGP Configuration
! Step 3b: iBGP neighbor added
! AS: 65001 | Router-ID: 172.20.0.2
! iBGP peer: k8s-bgp-speaker (172.20.0.3)
! ============================================
frr version 10.2.1_git
frr defaults traditional
hostname mac-speaker
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65001
 bgp router-id 172.20.0.2
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 172.20.0.3 remote-as 65001
 neighbor 172.20.0.3 description k8s-bgp-speaker
 !
 address-family ipv4 unicast
  neighbor 172.20.0.3 activate
 exit-address-family
!
line vty
!
